from typing import Union, Literal

# Define a type for the content generated by the language model
Content = str

# Define a type for the file formats supported by the application
FileType = Literal['png', 'pdf']

# Define a type for the response from the language model
LanguageModelResponse = dict[str, Union[str, list[str]]]

# Define a type for the agent's configuration settings
AgentConfig = dict[str, Union[str, int, float]]